name: deploy to lambda
on: [push]
jobs:
    deploy_zip:
        name: deploy lambda function
        runs-on: ubuntu-latest
        strategy:
            matrix:
                go-version: [1.13.x]
        steps:
            - name: checkout source code
              uses: actions/checkout@v1
            - name: Zip file
              run: |
                  cd aws-scripts && zip deployment.zip ec2-start-stop.js
            - name: default deploy
              uses: appleboy/lambda-action@master
              with:
                  aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws_region: ${{ secrets.AWS_REGION }}
                  function_name: ec2-start-stop
                  zip_file: aws-scripts/deployment.zip
